/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import civitas.Casilla;
import civitas.CivitasJuego;
import civitas.Dado;
import civitas.Diario;
import civitas.Jugador;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import civitas.Tablero;
import controladorCivitas.Respuesta;
//import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author juanma
 */
public class CivitasView extends javax.swing.JFrame implements vistaTextualCivitas.Vista {

    private CivitasJuego juego;
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowTitle = new javax.swing.JLabel();
        jugadorPanel = new GUI.JugadorPanel();
        siguienteOperacionLabel = new javax.swing.JLabel();
        siguienteOperacion = new javax.swing.JTextField();
        casillaPanel = new GUI.CasillaPanel();
        rankingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ranking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowTitle.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        windowTitle.setText("CIVITAS");
        getContentPane().add(windowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));
        getContentPane().add(jugadorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        siguienteOperacionLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        siguienteOperacionLabel.setText("SIGUIENTE OPERACIÓN:");
        getContentPane().add(siguienteOperacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        siguienteOperacion.setEditable(false);
        siguienteOperacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        getContentPane().add(siguienteOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));
        getContentPane().add(casillaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        rankingLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rankingLabel.setText("RANKING:");
        getContentPane().add(rankingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        ranking.setEditable(false);
        ranking.setColumns(20);
        ranking.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ranking.setRows(5);
        ranking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jScrollPane1.setViewportView(ranking);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void setCivitasJuego(CivitasJuego juego) {
        this.juego = juego;
        setVisible(true);
    }
    
    public void actualiza() {
        jugadorPanel.setJugador(juego.getJugadorActual());
        Tablero tablero = juego.getTablero();
        Casilla actual = tablero.getCasilla(juego.getJugadorActual().getCasillaActual());
        casillaPanel.setCasilla(actual);
        
        rankingLabel.setVisible(false);
        ranking.setVisible(false);
        
        if (juego.finalDelJuego()) {
            rankingLabel.setVisible(true);
            ranking.setVisible(true);
            
            ranking.setText("");
            
            for (Jugador j : juego.ranking()) {
                ranking.setText(ranking.getText() + "\n" + j.getNombre());
            }
        }
        
        repaint();
        revalidate();
    }

    public void pausa() {
        int val = JOptionPane.showConfirmDialog(null, "¿Continuar?",
                    "Siguiente paso", JOptionPane.YES_NO_OPTION);
        
        if (val == 1)
            System.exit(0);
    }

    public Respuesta comprar() {
        int opcion = 1 - JOptionPane.showConfirmDialog(null, "¿Quieres comprar"
                    + " la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        
        Respuesta r = Respuesta.NO;
        
        if (opcion == 1)
            r = Respuesta.SI;
        
        return r;
    }

    public OperacionInmobiliaria elegirOperacion() {
        GestionarDialog gestionarD = new GestionarDialog(this);
        
        return gestionarD.getGestion();
    }

    public int elegirPropiedad() {
        PropiedadDialog propiedadD = new PropiedadDialog(this, juego.getJugadorActual());
        
        return propiedadD.getPropiedad();
    }

    public void mostrarSiguienteOperacion(OperacionJuego operacion) {
        siguienteOperacion.setText(operacion.toString());
        
        if (operacion == OperacionJuego.AVANZAR)
            Dado.createInstance(this);
        
        repaint();
    }

    public void mostrarEventos() {
        if (!Diario.getInstance().getEventos().isEmpty()) {
            DiarioDialog diarioD = new DiarioDialog(this);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CasillaPanel casillaPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorPanel;
    private javax.swing.JTextArea ranking;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JTextField siguienteOperacion;
    private javax.swing.JLabel siguienteOperacionLabel;
    private javax.swing.JLabel windowTitle;
    // End of variables declaration//GEN-END:variables
}