
package GUI;

import civitas.CasillaCalle;
import civitas.Jugador;
import java.util.ArrayList;


public class JugadorPanel extends javax.swing.JPanel {
    
    Jugador jugador;    

    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugadorTitle = new javax.swing.JLabel();
        jNombreLabel = new javax.swing.JLabel();
        jSaldoLabel = new javax.swing.JLabel();
        jEspeculadorLabel = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jSaldo = new javax.swing.JTextField();
        jEspeculador = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        jugadorTitle.setText("JUGADOR");

        jNombreLabel.setText("Nombre:");

        jSaldoLabel.setText("Saldo:");

        jEspeculadorLabel.setText("Especulador:");

        jNombre.setEditable(false);
        jNombre.setText("jNombre");

        jSaldo.setEditable(false);
        jSaldo.setText("jSaldo");

        jEspeculador.setEditable(false);
        jEspeculador.setText("jEspeculador");

        propiedadesPanel.setLayout(new javax.swing.BoxLayout(propiedadesPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jugadorTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jEspeculadorLabel)
                                    .addComponent(jSaldoLabel)
                                    .addComponent(jNombreLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(propiedadesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jugadorTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombreLabel)
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaldoLabel)
                    .addComponent(jSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEspeculadorLabel)
                    .addComponent(jEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(propiedadesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    void setJugador(Jugador j) {
        jugador = j;
        jNombre.setText(jugador.getNombre());
        jSaldo.setText(Float.toString(jugador.getSaldo()));
        jEspeculador.setText(Boolean.toString(jugador.esEspeculador()));
        
        rellenaPropiedades(jugador.getPropiedades());
        
        repaint();
        revalidate();
    }
    
    private void rellenaPropiedades(ArrayList<CasillaCalle> lista) {
        propiedadesPanel.removeAll();
        
        for (CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        
        repaint();
        revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jEspeculador;
    private javax.swing.JLabel jEspeculadorLabel;
    private javax.swing.JTextField jNombre;
    private javax.swing.JLabel jNombreLabel;
    private javax.swing.JTextField jSaldo;
    private javax.swing.JLabel jSaldoLabel;
    private javax.swing.JLabel jugadorTitle;
    private javax.swing.JPanel propiedadesPanel;
    // End of variables declaration//GEN-END:variables
}
