/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author juanma
 */
public class PropiedadPanel extends javax.swing.JPanel {
    
    CasillaCalle tituloPropiedad;

    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNombreLabel = new javax.swing.JLabel();
        pNombre = new javax.swing.JTextField();
        pCasasLabel = new javax.swing.JLabel();
        pCasas = new javax.swing.JTextField();
        pHotelesLabel = new javax.swing.JLabel();
        pHoteles = new javax.swing.JTextField();

        pNombreLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        pNombreLabel.setText("Nombre:");
        add(pNombreLabel);

        pNombre.setEditable(false);
        pNombre.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        pNombre.setText("pNombre");
        add(pNombre);

        pCasasLabel.setText("Nº casas:");
        add(pCasasLabel);

        pCasas.setEditable(false);
        pCasas.setText("pCasas");
        add(pCasas);

        pHotelesLabel.setText("Nº hoteles:");
        add(pHotelesLabel);

        pHoteles.setEditable(false);
        pHoteles.setText("pHoteles");
        add(pHoteles);
    }// </editor-fold>//GEN-END:initComponents

    void setPropiedad(CasillaCalle casilla) {
        tituloPropiedad = casilla;
        pNombre.setText(tituloPropiedad.getNombre());
        pCasas.setText(Integer.toString(tituloPropiedad.getNumCasas()));
        pHoteles.setText(Integer.toString(tituloPropiedad.getNumHoteles()));
        
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField pCasas;
    private javax.swing.JLabel pCasasLabel;
    private javax.swing.JTextField pHoteles;
    private javax.swing.JLabel pHotelesLabel;
    private javax.swing.JTextField pNombre;
    private javax.swing.JLabel pNombreLabel;
    // End of variables declaration//GEN-END:variables
}
